  version: '3'
  services:
    web:
      image: ambientum/php:7.1-apache
      container_name: boteprafora-api
      volumes:
        - ./api:/var/www/app
      ports:
        - "80:8080"
      links:
        - mysql
      depends_on:
        - mysql

    mysql:
      image: mysql:5.7
      expose:
        - "3306"
      ports:
        - "3306:3306"

      volumes:
        - /var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laravel
